services:
  - type: worker
    name: best-veo3-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: starter
    region: frankfurt
    autoDeploy: true
