services:
  - type: web
    name: shubinfilms-best-veo3-bot
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: >
      gunicorn suno_web:app
      -k uvicorn.workers.UvicornWorker
      --bind 0.0.0.0:$PORT
      --access-logfile -
      --error-logfile -
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
  - type: worker
    name: best-veo3-bot
    env: python
    pythonVersion: 3.11.9
    buildCommand: pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt
    startCommand: python -u bot.py
    plan: starter
    region: frankfurt
    autoDeploy: true
